version: '3.9'
volumes:
  fast_vol:
services:
    fast-fest:
      container_name: fast-fest
      build:
        context: ./Docker
        dockerfile: Dockerfile
      image: fast-fest
      environment:
        - ENV=DEV
      ports:
        - "9501:9501"
      command:
        - "uvicorn"
        - "app:app"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "9501"
      volumes:
        - fast_vol:/app/backend/fast
